version: "3.9"

services: 
  # mongo
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=movie_database
    ports:
      - 27017:27017

  mongo_seed:
    build: ./mongo-seed
    depends_on:
        - mongodb

  # application
  web: 
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - mongodb

