version: "3.9"

services: 
  # mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017

  # application
  web: 
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"

